##############################################################################
#
#  Makefile for Hydra library libEventDispLay.so
#
#  This makefile contains all definitions local to this module. All
#  general definitions are included from makefiles in $(HADDIR).
#
##############################################################################

LIB_NAME := EventDisplay

SOURCE_FILES :=	hedhelpers.cc		\
                hedhitobjects.cc 	\
                hedgui.cc 		\
                hedfield.cc

include $(HADDIR)/hades.def.mk
include $(HADDIR)/hades.module.mk
