##############################################################################
#
#  Makefile for Hydra library libOnline.so
#
#  This makefile contains all definitions local to this module. All
#  general definitions are included from makefiles in $(HADDIR).
#
##############################################################################

LIB_NAME := Online

SOURCE_FILES :=	honlinemonhist.cc	       	\
		honlinemonstack.cc	       	\
		honlinetrendhist.cc	       	\
		honlinehistarray.cc	       	\
		honlineclientservercom.cc	\
		honlinemonclientmain.cc       	\
		honlinemonclienthist.cc       	\
		honlinemonclientcanvas.cc     	\
		honlinemonclienttab.cc        	\
		honlinemonclientsimplewin.cc  	\
		honlinemonclienttabwin.cc     	\
		honlinemonclientdet.cc        	\
		honlinemonclientmainwin.cc    	\
		honlinemonclientxml.cc



include $(HADDIR)/hades.def.mk
include $(HADDIR)/hades.module.mk
