##############################################################################
#
#  Makefile for Hydra library libAlignment.so
#
#  This makefile contains all definitions local to this module. All
#  general definitions are included from makefiles in $(HADDIR).
#
##############################################################################
LIB_NAME := Alignment

SOURCE_FILES :=	halignmentgdata.cc      \
		halignmentggeom.cc      \
		halignmentgbase.cc     \
		halignmentgparticlebase.cc \
		halignmentgparticle.cc  \
		halignmentgnomag.cc     \
		halignmentgcosmics.cc   \
		halignmentgrotations.cc \
		halignmentgshower.cc    \
		hmdccosmicscandidate.cc \
		halignmentmeta.cc	\
		Mille.cc                \
		hmdcmille.cc            
		
include $(HADDIR)/hades.def.mk
include $(HADDIR)/hades.module.mk
