APP_NAME     := TreeAnalysis
SOURCE_FILES := TreeAnalysis.cc
USES_RFIO    := yes
USES_CERNLIB := no
USES_ORACLE  := yes


include $(HADDIR)/hades.def.mk

# override default list of linked Hydra libraries - before they can act on the rules
HYDRA_LIBS += -lOraUtil

include $(HADDIR)/hades.app.mk
### possibly override default or append new rules here
