##############################################################################
#
#  Makefile for Hydra library libRpc.so
#
#  This makefile contains all definitions local to this module. All
#  general definitions are included from makefiles in $(HADDIR).
#
##############################################################################

LIB_NAME := Rpc

SOURCE_FILES :=	hrpcraw.cc		\
		hrpccontfact.cc	      	\
		hrpcdetector.cc	        \
		hrpcparrootfileio.cc  	\
		hrpcparasciifileio.cc 	\
		hrpccal.cc              \
		hrpccalsim.cc           \
		hrpccalpar.cc           \
		hrpccalibrater.cc       \
		hrpcchargeoffsetpar.cc  \
		hrpchit.cc              \
		hrpchitsim.cc           \
		hrpchitf.cc             \
		hrpccluster.cc          \
		hrpcclustersim.cc       \
		hrpcclusterf.cc         \
		hrpcclusfpar.cc         \
		hrpchitfpar.cc          \
		hrpcslewingpar.cc       \
		hrpctimepospar.cc       \
		hrpcdigipar.cc          \
		hrpcwtoqpar.cc          \
		hrpccellstatuspar.cc    \
		hrpcgeomcellpar.cc      \
		hrpcgeompar.cc          \
		hrpctrbunpacker.cc      \
		hrpctrb2unpacker.cc     \
		hrpctrb2lookup.cc       \
		hrpclookupgeom.cc       \
		hrpctaskset.cc          \
		hrpcdigitizer.cc

include $(HADDIR)/hades.def.mk
include $(HADDIR)/hades.module.mk
