##############################################################################
#
#  Makefile for Hydra library libRevt.so
#
#  This makefile contains all definitions local to this module. All
#  general definitions are included from makefiles in $(HADDIR).
#
##############################################################################

LIB_NAME := Revt

SOURCE_FILES :=	hldsockremotesource.cc	\
		hldsockremotevt.cc	\
		hrevbuffer.cc

include $(HADDIR)/hades.def.mk
include $(HADDIR)/hades.module.mk
