/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SERVER_H_RPCGEN
#define _SERVER_H_RPCGEN

#include <rpc/rpc.h>

#include "rpcbuf.h"

extern "C" bool_t xdr_rpcbuf(XDR *, rpcbuf*);

#define DAQPROG ((u_long)0x20000001)
#define DAQVERS ((u_long)1)

#define ONLINEEVT ((u_long)1)
extern "C" rpcbuf * onlineevt_1(void *, CLIENT *);

#endif /* !_SERVER_H_RPCGEN */
