/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <rpc/rpc.h>
#include "osf_server.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

rpcevt *
onlineevt_1(argp, clnt)
	void *argp;
	CLIENT *clnt;
{
	static rpcevt res;

	bzero((char *)&res, sizeof(res));
	if (clnt_call(clnt, ONLINEEVT, xdr_void, argp, xdr_rpcevt, &res, TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&res);
}
