##############################################################################
#
#  Makefile for Hydra library libOraUtil.so
#
#  This makefile contains all definitions local to this module. All
#  general definitions are included from makefiles in $(HADDIR).
#
##############################################################################

LIB_NAME := OraUtil

SOURCE_FILES :=	hdbcolumn.cc			\
		hdbcolumntype.cc		\
		hdbfileio.cc			\
		horaslowperiod.cc		\
		horaslowpartition.cc		\
		horaslowchanrunsum.cc		\
		horaslowchanmeta.cc		\
		horaslowchanraw.cc		\
		horaslowarchrateobj.cc		\
		horaslowchannel.cc		\
		horaslowmanager.cc		\
		hdbconn.pc			\
		hdbfileutil.pc			\
		hdbtable.pc			\
		horadetruninfoio.pc		\
		horaslowreader.pc		\
		horamagnetimport.pc

include $(HADDIR)/hades.def.mk
include $(HADDIR)/hades.module.mk
