##############################################################################
#
#  Makefile for Hydra library libPionTracker.so
#
#  This makefile contains all definitions local to this module. All
#  general definitions are included from makefiles in $(HADDIR).
#
##############################################################################

LIB_NAME := PionTracker

SOURCE_FILES :=	hpiontrackerdetector.cc		\
		hpiontrackerraw.cc		\
		hpiontrackercal.cc		\
		hpiontrackerhit.cc		\
		hpiontrackertrack.cc		\
		hpiontrackertaskset.cc		\
		hpiontrackertrb3unpacker.cc	\
		hpiontrackercalibrater.cc	\
		hpiontrackerhitf.cc		\
		hpiontrackertrackf.cc		\
		hpiontrackercontfact.cc		\
		hpiontrackerparasciifileio.cc	\
		hpiontrackerparrootfileio.cc	\
		hpiontrackertrb3lookup.cc	\
		hpiontrackercalpar.cc		\
		hpiontrackercalrunpar.cc      	\
		hpiontrackerhitfpar.cc		\
		hpiontrackertrackfpar.cc      	\
		hpiontrackermompar.cc           \
		hpiontrackermomrunpar.cc        \
		HBeam.cc   		   	\
		hpiontrackerbeampar.cc		\
		hpiontrackergeompar.cc

include $(HADDIR)/hades.def.mk
include $(HADDIR)/hades.module.mk
