##############################################################################
#
#  Makefile for Hydra library libParticle.so
#
#  This makefile contains all definitions local to this module. All
#  general definitions are included from makefiles in $(HADDIR).
#
##############################################################################

LIB_NAME := Particle

SOURCE_FILES :=	hparticlecand.cc        \
                hparticlecandsim.cc     \
                hparticlewallhit.cc     \
                hparticlewallhitsim.cc  \
                hparticlecal.cc		\
                hparticlemdc.cc     	\
                hparticleevtinfo.cc    	\
                hparticleevtchara.cc  	\
                hparticlecandfiller.cc	\
                hparticlecandfillerpar.cc \
                hparticletracksorter.cc \
                hparticletrackcleaner.cc  \
                hparticleevtinfofiller.cc \
                hparticlecontfact.cc 	\
                hparticlestart2hitf.cc 	\
                hparticletool.cc     	\
                hparticletree.cc 	\
                hparticleanglecor.cc 	\
                hparticlepair.cc 	\
                hparticlegeant.cc 	\
                hparticlegeantdecay.cc 	\
                hparticlegeantevent.cc 	\
                hparticlegeantpair.cc 	\
                hparticlepairdraw.cc 	\
                hparticlepairmaker.cc 	\
                hparticlebooker.cc 	\
                hparticlevertexfind.cc  \
                hparticlecut.cc 	\
                hparticlecutrange.cc 	\
		hparticlebt.cc          \
		hparticlebtringf.cc     \
		hparticlebtclusterf.cc  \
		hparticlebtring.cc  	\
		hparticlebtringinfo.cc  \
		hparticlebtangletrafo.cc\
		hparticlepathlengthcorr.cc \
		hparticlet0reco.cc      \
		hparticlebtpar.cc       \
		hparticlerunningmean.cc

include $(HADDIR)/hades.def.mk
include $(HADDIR)/hades.module.mk
