##############################################################################
#
#  Makefile for Hydra library libMdcUtil.so
#
#  This makefile contains all definitions local to this module. All
#  general definitions are included from makefiles in $(HADDIR).
#
##############################################################################

LIB_NAME := MdcUtil

SOURCE_FILES :=	hmdclowlevelqa.cc		\
		hmdcoffset.cc			\
		hmdcslope.cc			\
		hmdcselftracking.cc		\
		hmdcslopes.cc			\
		hmdctrackingeff.cc

include $(HADDIR)/hades.def.mk
include $(HADDIR)/hades.module.mk
