##############################################################################
#
#  Makefile for Hydra library libKalman.so
#
#  This makefile contains all definitions local to this module. All
#  general definitions are included from makefiles in $(HADDIR).
#
##############################################################################

LIB_NAME := Kalman
 
SOURCE_FILES :=hkaldetcradle.cc \
        hkaldafwire.cc \
        hkaldafsinglewire.cc \
        hkalfiltertask.cc \
        hkalfilt2d.cc \
        hkalfiltwire.cc \
        hkalifilt.cc \
        hkalgeomtools.cc \
        hkalhit.cc \
        hkalinput.cc \
        hkalmatrixtools.cc \
        hkalmdchit.cc \
        hkalmetamatch.cc \
        hkalmetamatcher.cc \
        hkalmixture.cc \
        hkalmdcmeaslayer.cc \
        hkalplane.cc \
        hkalrungekutta.cc \
        hkaltrack.cc \
        hkaltracksite.cc \
        hkaltrackstate.cc \
        hmaterials.cc

include $(HADDIR)/hades.def.mk
include $(HADDIR)/hades.module.mk
