##############################################################################
#
#  Makefile for Hydra library libMdcGarfield.so
#
#  This makefile contains all definitions local to this module. All
#  general definitions are included from makefiles in $(HADDIR).
#
##############################################################################

LIB_NAME := DiskSpace
SOURCE_FILES :=	hdiskspace.cc

include $(HADDIR)/hades.def.mk
include $(HADDIR)/hades.module.mk
