##############################################################################
#
#  Makefile for Hydra library libSimulation.so
#
#  This makefile contains all definitions local to this module. All
#  general definitions are included from makefiles in $(HADDIR).
#
##############################################################################

LIB_NAME := Simulation

SOURCE_FILES :=	hgeominterface.cc	\
		hgeomio.cc		\
		hgeomasciiio.cc		\
		hgeombuilder.cc		\
		hgeomrootbuilder.cc	\
		hgeommedia.cc		\
		hgeommedium.cc		\
		hgeomnode.cc		\
		hgeomset.cc		\
		hgeomhit.cc		\
		hgeomcave.cc		\
		hgeomsectors.cc		\
		hgeomcoils.cc		\
		hgeomframes.cc		\
		hgeomtarget.cc		\
		hgeommdc.cc		\
		hgeommdchit.cc		\
		hgeomtof.cc		\
		hgeomtofhit.cc		\
		hgeomrich.cc		\
		hgeomrichhit.cc		\
		hgeomshower.cc		\
		hgeomshowerhit.cc	\
		hgeomstart.cc		\
		hgeomstarthit.cc	\
		hgeomfwall.cc		\
		hgeomfwallhit.cc	\
		hgeomuser.cc		\
		hgeomuserhit.cc		\
		hgeomrpc.cc		\
		hgeomrpchit.cc		\
		hgeomemc.cc		\
		hgeomemchit.cc		\
		hgeomfwdet.cc		\
		hgeomfwdethit.cc	\
		hgeommdcwireplanes.cc	\
		hgeommdcwire.cc

include $(HADDIR)/hades.def.mk
include $(HADDIR)/hades.module.mk
