##############################################################################
#
#  Makefile for Hydra library libShower.so
#
#  This makefile contains all definitions local to this module. All
#  general definitions are included from makefiles in $(HADDIR).
#
##############################################################################

LIB_NAME := Shower

SOURCE_FILES :=	hshowercal.cc			\
		hshowercalpar.cc		\
		hshowercalibrater.cc		\
		hshowerraw.cc			\
		hshowerunpacker.cc		\
		hshowergeantreader.cc		\
		hshowercalparcell.cc		\
		hshowergeantwire.cc		\
		hshowerframe.cc			\
		hshowerwiretab.cc		\
		hshowerpad.cc			\
		hshowerdigipar.cc		\
		hshowerdigitizer.cc		\
		hshowerhitdigitizer.cc		\
		hshowerpaddigitizer.cc		\
		hshowerhit.cc			\
		hshowerhitfinder.cc		\
		hshowerhitfpar.cc		\
		hshowerhitheader.cc		\
		hshowerdetector.cc		\
		hshowergeompar.cc		\
		hshowergeometry.cc		\
		hshowercontfact.cc		\
		hshowerparasciifileio.cc	\
		hshowerparrootfileio.cc		\
		hshowerpid.cc			\
		hshowertrack.cc			\
		hshowertaskset.cc		\
		hshowerhistcell.cc		\
		hshowerhist.cc			\
		hshowercalparcalculator.cc	\
		hshowerrawhist.cc		\
		hshowercalhist.cc		\
		hshowerhithist.cc		\
		hshowercopy.cc			\
		hgeomvector2.cc			\
		hshowerhitsim.cc		\
		hshowerpidtrack.cc		\
		hshowerhittrackmatcher.cc	\
		hshowerpidtrackmatcher.cc	\
		hshowercriterium.cc		\
		hshowerparticleidentifier.cc

include $(HADDIR)/hades.def.mk
include $(HADDIR)/hades.module.mk
