##############################################################################
#
#  Makefile for Hydra library libMdcTrackD.so
#
#  This makefile contains all definitions local to this module. All
#  general definitions are included from makefiles in $(HADDIR).
#
##############################################################################

LIB_NAME := MdcTrackD

SOURCE_FILES :=	hmdctrackdcontfact.cc	\
		hmdcgeomobj.cc		\
		hmdcsizescells.cc	\
		hmdclayer.cc		\
		hmdcclfnstack.cc	\
		hmdcclus.cc		\
		hmdcclussim.cc		\
		hmdccluster.cc          \
		hmdclookuptb.cc		\
		hmdc34clfinder.cc	\
		hmdcefficiency.cc	\
		hmdctrackfinder.cc	\
		hmdctrackdset.cc	\
		hmdcclustertohit.cc	\
		hmdctbarray.cc		\
		hmdclistcells.cc	\
		hmdclistgroupcells.cc	\
		hmdcgetcontainers.cc	\
		hmdctrackfitter.cc	\
		hmdctrackfittera.cc	\
		hmdc12fit.cc		\
		hmdctrackfitpar.cc	\
		hmdcclusfit.cc		\
		hmdcwirefit.cc		\
		hmdceffmenu.cc		\
		hmdctargetmon.cc	\
		hmdcclusinf.cc		\
		hmdcclusinfsim.cc	\
		hmdcrichcorr.cc		\
		hmdchitsegfiller.cc	\
		hseqarr.cc		\
		hmdcstoreevents.cc	\
		hmdcdedx2.cc		\
		hmdcdedx2maker.cc	\
		hmdcalignerd.cc		\
		hmdcalignerparam.cc	\
		hmdcclusfitsim.cc	\
		hmdcdrifttimepar.cc	\
		hmdcidealtracking.cc	\
		hmdcminimize.cc		\
		hmdctrackfitterb.cc	\
		hmdctrackparam.cc	\
		hmdcwiredata.cc		\
		hmdcwirefitsim.cc	\
		hmdcclustfromseg.cc	\
		hmdcgeanttrack.cc	\
		hmdclayercorrpar.cc	\
		hmdcclusmetamatch.cc    \
		hmdckickplane.cc        \
                hmdckickcor.cc


# removed from Makefile, but not from CVS
#		hmdctrackfitterh.cc

include $(HADDIR)/hades.def.mk
include $(HADDIR)/hades.module.mk
