##############################################################################
#
#  Makefile for Hydra library libWall.so
#
#  This makefile contains all definitions local to this module. All
#  general definitions are included from makefiles in $(HADDIR).
#
##############################################################################

LIB_NAME := Wall

SOURCE_FILES :=	hwalldetector.cc	\
		hwalltaskset.cc		\
		hwallunpacker.cc	\
		hwallraw.cc		\
		hwallcontfact.cc	\
		hwallparrootfileio.cc	\
		hwallparasciifileio.cc	\
		hwalllookup.cc		\
		hwallcal.cc		\
		hwallcalpar.cc		\
		hwallcalibrater.cc	\
		hwalldigitizer.cc	\
		hwallrawsimfilter.cc	\
		hwallrawsim.cc		\
		hwallonehit.cc		\
		hwallhit.cc		\
		hwalleventplane.cc     	\
		hwallhitsim.cc		\
		hwallhitf.cc		\
	        hwalleventplanef.cc   	\
	        hwallonehitf.cc		\
		hwallrefwinpar.cc	\
		hwalldigipar.cc		\
		hwalleventplanepar.cc 	\
		hwallhitfsim.cc		\
		hwallgeompar.cc		\
		hwalltrbunpacker.cc 	\
		hwalltrb2unpacker.cc 	\
		hwalltrb2lookup.cc 	

include $(HADDIR)/hades.def.mk
include $(HADDIR)/hades.module.mk
