##############################################################################
#
#  Makefile for Hydra library libShowerUtil.so
#
#  This makefile contains all definitions local to this module. All
#  general definitions are included from makefiles in $(HADDIR).
#
##############################################################################

LIB_NAME := ShowerUtil

SOURCE_FILES :=	hsuprogressrec.cc	\
		hsuhldinfo.cc		\
		hsuerrorhandler.cc	\
		hsupaddivider.cc	\
		hsuchain.cc

include $(HADDIR)/hades.def.mk
include $(HADDIR)/hades.module.mk
