##############################################################################
#
#  Makefile for Hydra library libRich.so
#
#  This makefile contains all definitions local to this module. All
#  general definitions are included from makefiles in $(HADDIR).
#
##############################################################################

LIB_NAME := Rich

SOURCE_FILES := hrichanalysis.cc		\
		hrichanalysispar.cc		\
		hrichanalysissim.cc		\
		hrichcal.cc			\
		hrichcalpar.cc			\
		hrichcalparcell.cc		\
		hrichcalsim.cc			\
		hrichcontfact.cc		\
		hrichdetector.cc		\
		hrichdigitisationpar.cc		\
		hrichdigitizer.cc		\
		hrichdirclus.cc			\
		hrichframe.cc			\
		hrichframecorner.cc		\
		hrichframetab.cc		\
		hrichgeometrypar.cc		\
		hrichhit.cc			\
		hrichhitcandidate.cc		\
		hrichhitheader.cc		\
		hrichhitsim.cc			\
		hrichlabel.cc			\
		hrichmappingpar.cc		\
		hrichpad.cc			\
		hrichpadcorner.cc		\
		hrichpadtab.cc			\
		hrichpadclean.cc		\
		hrichpadfilter.cc		\
		hrichpadgraph.cc		\
		hrichpadlabel.cc		\
		hrichpadsignal.cc		\
		hrichparasciifileio.cc		\
		hrichparrootfileio.cc		\
		hrichringfind.cc		\
		hrichringfindsim.cc		\
		hrichtaskset.cc			\
		hrichthresholdpar.cc	        \
		hrichtrack.cc			\
		hrichunpacker.cc		\
		hrichwire.cc			\
		hrichwiretab.cc			\
		hrichwiresignal.cc		\
		hrich700taskset.cc    		\
		hrich700eventdisplay.cc	        \
		hrich700drawhist.cc		\
		hrich700utils.cc		\
		hrich700geotestqa.cc		\
		hrich700histmanager.cc		\
		hrich700pmt.cc 			\
		hrich700digitizer.cc 		\
		hrich700digipar.cc 		\
		hrich700ringfinderpar.cc	\
		hrich700ringfinderideal.cc 	\
		hrich700ringfittercop.cc 	\
		hrich700ringfinderhough.cc 	\
		hrich700recoqa.cc \
		hrich700digiparcreator.cc

DEBUG_LEVEL := 0

include $(HADDIR)/hades.def.mk
include $(HADDIR)/hades.module.mk
