##############################################################################
#
#  Makefile for Hydra library libStart.so
#
#  This makefile contains all definitions local to this module. All
#  general definitions are included from makefiles in $(HADDIR).
#
##############################################################################

LIB_NAME := Start

SOURCE_FILES :=	hlatchunpacker.cc	\
		hstart2cal.cc		\
		hstart2calibrater.cc	\
		hstart2calpar.cc	\
		hstart2detector.cc	\
		hstart2hit.cc		\
		hstart2hitf.cc		\
		hstart2hitfsim.cc     	\
		hstart2hitfpar.cc	\
		hstart2geompar.cc	\
		hstart2digipar.cc	\
		hstart2calrunpar.cc	\
		hstart2raw.cc		\
		hstart2trb2lookup.cc	\
		hstart2trb2unpacker.cc	\
		hstart2trb3lookup.cc	\
		hstart2trb3unpacker.cc	\
		hstart2trb3calpar.cc	\
		hstartcontfact.cc	\
		hstartparasciifileio.cc	\
		hstartparrootfileio.cc	\
		hstarttaskset.cc	\
		htboxchan.cc		\
		htboxdetector.cc	\
		htboxunpacker.cc


include $(HADDIR)/hades.def.mk
include $(HADDIR)/hades.module.mk
