##############################################################################
#
#  Makefile for Hydra library libTools.so
#
#  This makefile contains all definitions local to this module. All
#  general definitions are included from makefiles in $(HADDIR).
#
##############################################################################

LIB_NAME := Tools

USES_RFIO ?= yes

SOURCE_FILES := ptools.cc mptools.cc hptools.cc hreport.cc

include $(HADDIR)/hades.def.mk
include $(HADDIR)/hades.module.mk
