##############################################################################
#
#  Makefile for Hydra library libMdc.so
#
#  This makefile contains all definitions local to this module. All
#  general definitions are included from makefiles in $(HADDIR).
#
##############################################################################

LIB_NAME := Mdc

SOURCE_FILES :=	hmdcbitflipcor.cc	\
		hmdcbitflipcorpar.cc	\
		hmdccal1.cc		\
		hmdccal1sim.cc		\
		hmdccal2.cc		\
		hmdccal2par.cc		\
		hmdccal2parsim.cc	\
		hmdccal2sim.cc		\
		hmdccalibrater1.cc	\
		hmdccalparraw.cc	\
		hmdccelleff.cc		\
		hmdccellgroup.cc	\
		hmdccontfact.cc		\
		hmdccutstat.cc		\
		hmdcdetector.cc		\
		hmdcdigitizer.cc	\
		hmdcdigitpar.cc		\
		hmdcgeantcell.cc	\
		hmdcgeantreader.cc	\
		hmdcgeompar.cc		\
		hmdcgeomstruct.cc	\
		hmdchit.cc		\
		hmdchitsim.cc		\
		hmdcidealclasses.cc	\
		hmdclayergeompar.cc	\
		hmdclookupgeom.cc	\
		hmdclookupraw.cc	\
		hmdcparasciifileio.cc	\
		hmdcparrootfileio.cc	\
		hmdcppevtfilter.cc	\
		hmdcraw.cc		\
		hmdcrawcor.cc		\
		hmdcraweventheader.cc	\
		hmdcrawstruct.cc	\
		hmdcseg.cc		\
		hmdcsegsim.cc		\
		hmdcsetup.cc		\
		hmdctaskset.cc		\
		hmdctdcchannel.cc	\
		hmdctdcthreshold.cc	\
		hmdctimecut.cc		\
		hmdctrk.cc		\
		hmdctrkcand.cc		\
		hmdcvertexfind.cc	\
		hmdcwirestat.cc		\
		hmdcvertexwriter.cc	\
		hmdcunpackerpar.cc	\
		hmdcunpacker.cc		\
		hmdcdataword.cc	\
		hmdcoepaddrcorrpar.cc	\
		hmdcoepstatusdata.cc

include $(HADDIR)/hades.def.mk
include $(HADDIR)/hades.module.mk
