##############################################################################
#
#  Makefile for Hydra library libMdcGarfield.so
#
#  This makefile contains all definitions local to this module. All
#  general definitions are included from makefiles in $(HADDIR).
#
##############################################################################

LIB_NAME := MdcGarfield

SOURCE_FILES :=	hmdcgarmacromaker.cc	\
		hmdcgarcal2maker.cc	\
		hmdcgarsignalreader.cc	\
		hmdcgareffmaker.cc	\
		hmdcgarreader.cc	\
		hfield.cc

include $(HADDIR)/hades.def.mk
include $(HADDIR)/hades.module.mk
