##############################################################################
#
#  Makefile for Hydra library libOraSim.so
#
#  This makefile contains all definitions local to this module. All
#  general definitions are included from makefiles in $(HADDIR).
#
##############################################################################

LIB_NAME := OraSim

SOURCE_FILES := hgeomora2io.pc hgeomora2conn.pc

include $(HADDIR)/hades.def.mk
include $(HADDIR)/hades.module.mk
