##############################################################################
#
#  Makefile for Hydra library libOra.so
#
#  This makefile contains all definitions local to this module. All
#  general definitions are included from makefiles in $(HADDIR).
#
##############################################################################

LIB_NAME := Ora

SOURCE_FILES :=	hparora2io.cc		\
		hparora2set.cc		\
		hora2geomdetversion.cc	\
		hora2geomobj.cc		\
		hora2conn.pc		\
		hora2info.pc		\
		hdetparora2io.pc	\
		hcondparora2io.pc	\
		hspecparora2io.pc	\
		hmdcparora2io.pc	\
		hrichparora2io.pc	\
		htofparora2io.pc	\
		hshowerparora2io.pc	\
		hstartparora2io.pc	\
		hwallparora2io.pc	\
		hrpcparora2io.pc	\
		hemcparora2io.pc	\
		hpiontrackerparora2io.pc

include $(HADDIR)/hades.def.mk
include $(HADDIR)/hades.module.mk
