##############################################################################
#
#  Makefile for Hydra library libEmc.so
#
#  This makefile contains all definitions local to this module. All
#  general definitions are included from makefiles in $(HADDIR).
#
##############################################################################

LIB_NAME := Emc

SOURCE_FILES := hemcdetector.cc         \
                hemcraw.cc              \
                hemccal.cc              \
                hemccalsim.cc           \
                hemccluster.cc          \
                hemcclustersim.cc          \
                hemctaskset.cc          \
		hemctrb3unpacker.cc	\
		hemccalibrater.cc	\
                hemcdigitizer.cc        \
                hemcclusterf.cc         \
		hemccontfact.cc		\
		hemcparrootfileio.cc	\
		hemcparasciifileio.cc	\
		hemctrb3lookup.cc	\
		hemccalpar.cc		\
		hemcgeompar.cc		\
		hemccellgeompar.cc	\
		hemcdigipar.cc

include $(HADDIR)/hades.def.mk
include $(HADDIR)/hades.module.mk
