
APP_NAME     := run_delta
SOURCE_FILES := analysis.cc


USES_ORACLE=yes
USES_GFORTRAN=yes
USES_RFIO=no

Target:  clean build install

include $(HADDIR)/hades.def.mk
#HYDRA_LIBS +=

include $(HADDIR)/hades.app.mk
