##############################################################################
#
#  Makefile for Hydra library libMdcTrackG.so
#
#  This makefile contains all definitions local to this module. All
#  general definitions are included from makefiles in $(HADDIR).
#
##############################################################################

LIB_NAME := MdcTrackG

SOURCE_FILES :=	hmdctrackgfield.cc		\
		hmdctrackgcorrections.cc	\
		hmdctrackgcorrpar.cc		\
		hmdctrackgfieldpar.cc		\
		hmdctrackgspline.cc		\
		hmdctrackgcontfact.cc		\
		hbasetrack.cc			\
		hmetamatch2.cc			\
		hmetamatchF2.cc			\
		hmetamatchpar.cc		\
		hsplinetrack.cc			\
		hsplinetrackF2.cc		\
		hrungekutta.cc			\
		hrktrackB.cc			\
		hrktrackBF2.cc			\
		hsplinetaskset.cc		\
		hsplinetofclF2.cc		\
		henergylosscorrpar.cc           \
		hlvl1evtfilter.cc		\
		htimelvl1evtfilter.cc		\
		hsplinepar.cc

include $(HADDIR)/hades.def.mk
include $(HADDIR)/hades.module.mk
