##############################################################################
#
#  Makefile for Hydra library libFwDet.so
#
#  This makefile contains all definitions local to this module. All
#  general definitions are included from makefiles in $(HADDIR).
#
##############################################################################

LIB_NAME := FwDet

SOURCE_FILES := hfwdetdetector.cc         \
                hfwdetcontfact.cc         \
                hfwdetparrootfileio.cc    \
                hfwdetparasciifileio.cc   \
                hfwdetgeompar.cc          \
                hfwdettaskset.cc          \
                hfwdetrpcgeompar.cc       \
                hfwdetrpccal.cc           \
                hfwdetrpccalsim.cc        \
                hfwdetrpcdigitizer.cc     \
                hfwdetrpcdigipar.cc       \
                hfwdetrpchit.cc           \
                hfwdetrpchitfinder.cc     \
                hfwdetrpchitfinderpar.cc  \
                hfwdetscincal.cc          \
                hfwdetscincalsim.cc       \
                hfwdetscindigitizer.cc    \
                hfwdetscindigipar.cc      \
                hfwdetstrawgeompar.cc	  \
                hfwdetstrawcal.cc         \
                hfwdetstrawcalsim.cc      \
                hfwdetstrawdigitizer.cc   \
                hfwdetstrawdigipar.cc     \
                hfwdetvectorfinder.cc     \
                hfwdetvectorfinderpar.cc  \
                hvectorcand.cc            \
                hvectorcandsim.cc

include $(HADDIR)/hades.def.mk
include $(HADDIR)/hades.module.mk
