##############################################################################
#
#  Makefile for Hydra library libQA.so
#
#  This makefile contains all definitions local to this module. All
#  general definitions are included from makefiles in $(HADDIR).
#
##############################################################################

LIB_NAME := QA

SOURCE_FILES :=	hqahistograms.cc	\
		hqamaker.cc		\
		hqaoutputps.cc		\
		hqavariations.cc	\
		hqascalers.cc

include $(HADDIR)/hades.def.mk
include $(HADDIR)/hades.module.mk
